=== gbax/RunaWFE-4.x/org.jbpm.ui/schema/forms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://runa.ru/xml" xmlns="http://runa.ru/xml" elementFormDefault="qualified">
	<xs:element name="forms">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="form" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="variable" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="format" type="xs:string" default="org.jbpm.web.formgen.format.DefaultFormat"/>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="optional" type="xs:string" use="optional" default="false"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="file" type="xs:string" use="optional"/>
						<xs:attribute name="state" type="xs:string" use="required"/>
						<xs:attribute name="type" type="xs:string" default="html"/>
						<xs:attribute name="validationFile" type="xs:string" use="optional"/>
						<xs:attribute name="jsValidation" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="scriptFile" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gbax/RunaWFE-4.x/branches/preview/gpd/demo/workspace/Demo - Other/src/process/ExecuteFormulaDemo/forms.xml
<?xml version="1.0" encoding="UTF-8"?>
<forms xmlns="http://runa.ru/xml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://runa.ru/xml forms.xsd">
  <form file="state2.ftl" jsValidation="false" state="state2" type="ftl" validationFile="state2.validation.xml"/>
  <form file="state3.ftl" jsValidation="false" state="state3" type="ftl" validationFile="state3.validation.xml"/>
  <form file="state4.ftl" jsValidation="false" state="state4" type="ftl" validationFile="state4.validation.xml"/>
  <form file="state5.ftl" jsValidation="false" state="state5" type="ftl" validationFile="state5.validation.xml"/>
  <form file="state6.ftl" jsValidation="false" state="state6" type="ftl" validationFile="state6.validation.xml"/>
  <form file="state1.ftl" jsValidation="false" state="state1" type="ftl" validationFile="state1.validation.xml"/>
  <form file="state7.ftl" jsValidation="false" state="state7" type="ftl" validationFile="state7.validation.xml"/>
  <form file="state8.ftl" jsValidation="false" state="state8" type="ftl" validationFile="state8.validation.xml"/>
  <form file="state9.ftl" jsValidation="false" state="state9" type="ftl" validationFile="state9.validation.xml"/>
</forms>
