=== gbax/RunaWFE-4.x/org.jbpm.ui/schema/orgfunctions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://runa.ru/xml" xmlns="http://runa.ru/xml" elementFormDefault="qualified">
	<xs:element name="functions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="function" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
						<xs:attribute name="name" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gbax/RunaWFE-4.x/branches/preview/gpd/demo/workspace/Demo - Bots/src/process/MSWordReport/orgfunctions.xml
<?xml version="1.0" encoding="UTF-8"?>
<functions xmlns="http://runa.ru/xml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://runa.ru/xml orgfunctions.xsd">
  <function
    function="ru.runa.wfe.bp.commons.EmployeeOrRequestorFunction" name="EmployeeOrRequestorFunction"/>
  <function function="ru.runa.wfe.bp.commons.DepartamentChiefFunction" name="DepartamentChiefFunction"/>
  <function function="ru.runa.bp.org.AlfDepartmentChiefOrgFunction" name="AlfDepartmentChiefOrgFunction"/>
  <function function="ru.runa.bp.org.AlfChiefOrgFunction" name="AlfChiefOrgFunction"/>
  <function function="ru.runa.bp.org.AlfEmployeeOrRequestorOrgFunction" name="AlfEmployeeOrRequestorOrgFunction"/>
  <function function="ru.runa.bp.org.AlfDirectorOrgFunction" name="AlfDirectorOrgFunction"/>
  <function function="ru.runa.af.organizationfunction.ChiefFunction" name="ChiefFunction"/>
  <function function="ru.runa.af.organizationfunction.DemoChiefFunction" name="DemoChiefFunction"/>
  <function
    function="ru.runa.af.organizationfunction.ExecutorByCodeFunction" name="ExecutorByCodeFunction"/>
  <function function="ru.runa.af.organizationfunction.DirectorFunction" name="DirectorFunction"/>
  <function
    function="ru.runa.af.organizationfunction.ExecutorByNameFunction" name="ExecutorByNameFunction"/>
  <function function="ru.runa.af.organizationfunction.SQLFunction" name="SQLFunction"/>
</functions>
